import { readFileSync } from 'node:fs';

const css = readFileSync(new URL('../../build/lazy-ui.css', import.meta.url), 'utf8');

const selectors = [
    '.alert',
    '.aura',
    '.avatar',
    '.badge',
    '.breadcrumbs',
    '.btn',
    '.cally',
    '.card',
    '.carousel',
    '.chat',
    '.checkbox',
    '.collapse',
    '.countdown',
    '.diff',
    '.divider',
    '.dock',
    '.drawer',
    '.dropdown',
    '.fab',
    '.fieldset',
    '.file-input',
    '.filter',
    '.footer',
    '.hero',
    '.hover-3d',
    '.hover-gallery',
    '.indicator',
    '.input',
    '.join',
    '.kbd',
    '.label',
    '.list',
    '.loading',
    '.mask',
    '.megamenu',
    '.menu',
    '.menu-active',
    '.menu-disabled',
    '.mockup-browser',
    '.mockup-code',
    '.mockup-phone',
    '.mockup-window',
    '.modal',
    '.navbar',
    '.otp',
    '.progress',
    '.radial-progress',
    '.radio',
    '.range',
    '.rating',
    '.select',
    '.skeleton',
    '.stack',
    '.stat',
    '.stats',
    '.status',
    '.steps',
    '.swap',
    '.tabs',
    '.table',
    '.text-rotate',
    '.textarea',
    '.theme-controller',
    '.timeline',
    '.toast',
    '.toggle',
    '.tooltip',
    '.validator',
    '.validator-hint',

    '.btn-primary',
    '.btn-xl',
    '.btn-soft',
    '.btn-dash',
    '.badge-soft',
    '.badge-dash',
    '.alert-soft',
    '.alert-dash',
    '.input-xl',
    '.card-border',
    '.card-sm',
    '.dock-xl',
    '.dropdown-center',
    '.dropdown-close',
    '.modal-top',
    '.modal-end',
    '.stack-top',
    '.stack-bottom',
    '.stack-start',
    '.stack-end',
    '.tooltip-content',
    '.step-icon',
    '.tabs-box',
    '.tabs-border',
    '.tabs-lift',
    '.menu-xl',
    '.range-vertical',
    '.rating-xl',
    '.table-xl',
    '.mask-parallelogram',
];

const missing = selectors.filter((selector) => !css.includes(selector));

if (missing.length) {
    console.error('Missing compiled Lazy UI classes:', missing.join(', '));
    process.exit(1);
}

console.log(`Tailwind/daisyUI smoke test passed (${selectors.length} selectors)`);
